### ISSUE TITLE
[Newfeeds] category 별로 같은 포스트가 여러번 보이는 현상 변경 요청

### ISSUE THREAD

**Issue by jeongdaeun98** [juhyeon96/Sns-timeline#105]
category가 달라도 여러개 보이는 것 보다 한번만 보였으면 좋겠습니다.
따라서 중요도를 댓글 > 좋아요 > post 이렇게 해서 한번만 보이게 하는 건 어떻게 생각하나요?
댓글, 좋아요 ,post 중 가장 최신인 정보를 보여주는 방법도 있습니다.

**Comment by juhyeon96** [comment]
댓글, 좋아요, post 중 가장 최신으로 1번만 보여주는 방법 구현하겠습니다
