### ISSUE TITLE
[MainPage] response body question

### ISSUE THREAD

**Issue by jeongdaeun98** [juhyeon96/Sns-timeline#80]
### **[present] response body**

> {
      "sender": "wngus",
      "category": "comment",
      "feed": {
        "postId": 44,
        "content": "남이 쓴 public 글입니다",
        "showLevel": "public",
        "timestamp": "2019.12.28",
        "totalTag": 0,
        "totalComment": 1,
        "totalLike": 2,
        "profile": {
          "name": "피자",
          "profile": "temp-url: aws s3"
        },
        "files": [],
        "tags": []
      },
      "comment": [
        {
          "postId": 44,
          "content": "pizza가 쓴 public글에 단 댓글. 이건 나를 팔로한 사람들 뉴스피드에서 보여아하는 글이다",
          "timestamp": "8분 전",
          "profile": {
            "name": "주현",
            "profile": "temp-url: aws s3"
          }
        }
      ]
    }
### **[I want] response body **

> {
      "sender": { username:"wngus",
                        nickname : "피자" },
      "category": "comment",
      "feed": {
        "postId": 44,
        "content": "남이 쓴 public 글입니다",
        "showLevel": "public",
        "timestamp": "2019.12.28",
        "totalTag": 0,
        "totalComment": 1,
        "totalLike": 2,
        "profile": {
          "name": "피자",
          "profile": "temp-url: aws s3",
           "id" : "wngus"
        },
        "files": [],
        "tags": []
      },
      "comment": [
        {
          "postId": 44,
          "content": "pizza가 쓴 public글에 단 댓글. 이건 나를 팔로한 사람들 뉴스피드에서 보여아하는 글이다",
          "timestamp": "8분 전",
          "profile": {
            "name": "주현",
            "profile": "temp-url: aws s3"
          }
        }
      ]
    }

사용자의 친구가 다른 유저가 쓴 게시물에 댓글을 달 경우 그 게시물을 쓴 유저의 아이디도 필요합니다. 또한 sender의 닉네임으로 포스팅 상태를 표시하는 것이 좀 더 사용자 입장에서 친근하게 다가올 것 같습니다.

>

**Comment by juhyeon96** [comment]
https://github.com/juhyeon96/Sns-timeline/pull/82 에서 반영하였습니다.
