### ISSUE TITLE
[newsfeed , post] 댓글창 상태 관리를 위한 초기값 추가

### ISSUE THREAD

**Issue by jeongdaeun98** [juhyeon96/Sns-timeline#89]
댓글창 상태 관리를 위해 초기값을 추가해주시면 감사하겠습니다.
islike 와 같은 depth로 부탁드립니다.
commentState : 'none' 
이렇게 추가 요청 부탁드립니다.

**Comment by jeongdaeun98** [comment]
확인했습니다.
댓글창 상태 관리를 위해 페이지 초기값을 추가해주시면 감사하겠습니다.
commentState 와 같은 depth로 부탁드립니다.
commentPage : 1
이렇게 추가 요청 부탁드립니다.

**Comment by juhyeon96** [comment]
#92 #93 두번에 걸쳐 반영하였습니다.
